### ISSUE TITLE
It has been a couple of years since v2.24.0. Any chance a new version will be tagged soon?

### ISSUE THREAD

**Issue by gh-andre** [intel/isa-l_crypto#128]
There are some useful fixes in the recent commits, like those alignment fixes, and it would be nice to be able to update the library based on what you consider a reasonably well tested revision. Thoughts?

**Comment by pablodelara** [comment]
Hi @gh-andre. There has been a team change at Intel working at this project and we are currently ramping up on it. We are working towards releasing around Q2 next year (we are looking into releasing ISA-L (https://github.com/intel/isa-l) in Q1 first, then ISA-L Crypto).

**Comment by gh-andre** [comment]
@pablodelara Thank you for responding. Looking forward to the new release.
