### ISSUE TITLE
failure on make test 

### ISSUE THREAD

**Issue by hzhuang1** [intel/isa-l_crypto#137]
aes/xts_128_rand
aes_xts_128 enc/dec rand test, 10 sets of 1048576 max: ...........fail rand 0, size 308598
make: *** [Makefile:6751: aes/xts_128_rand.run] Error 255

**Comment by hzhuang1** [comment]
It's tested on aarch64 platform.

**Comment by pablodelara** [comment]
Hi @hzhuang1. Did you test on the latest head? We just pushed a fix for this issue.

**Comment by hzhuang1** [comment]
Yes, it's fixed now. Let me close it.
