### ISSUE TITLE
Build failed, mh_sha1/mh_sha1_base_aliases.c not exist

### ISSUE THREAD

**Issue by machelcheng** [intel/isa-l_crypto#21]
# make
Building isa-l_crypto.h
make --no-print-directory all-am
  CC       sha1_mb/sha1_ctx_base_aliases.lo
make[1]: *** No rule to make target 'mh_sha1/mh_sha1_base_aliases.c', needed by 'mh_sha1/mh_sha1_base_aliases.lo'.  Stop.
Makefile:2159: recipe for target 'all' failed
make: *** [all] Error 2

#ls mh_sha1/mh_sha1_base_aliases.c
ls: cannot access 'mh_sha1/mh_sha1_base_aliases.c': No such file or directory

I use current master branch, and i make sure this file is not exist

**Comment by gbtucker** [comment]
Looks like there was a typo in the name of this file and the option for "base functions only" have not been tested.  I put a PR #22 to fix the name but I'm not sure the base_aliases were set up correctly when the multi-arch support was added by @haoyu01.  Can you try the PR and for just this unit? 
`make -f Makefile.unx units=mh_sha1`

**Comment by haoyu01** [comment]
@gbtucker 
I have tried your PR #22  . And I have added some comments . 

And mh_sha1 can build pass on ppc64le platform .
Other module still have problem .

**Comment by haoyu01** [comment]
@machelcheng 
Please take a look at https://github.com/intel/isa-l_crypto/commit/ffd20d8c8ff2f2ef0a5885b6d47bbbcf1ab393d3 . 
The patch is verified on aarch64 . And to add ppc64le support , please modify the files like aarch64 .

You should modify configure.ac and Makefile.am . 
To obtain best performance , you should add optimized code for ppc64le .

**Comment by machelcheng** [comment]
> @machelcheng
> Please take a look at [ffd20d8](https://github.com/intel/isa-l_crypto/commit/ffd20d8c8ff2f2ef0a5885b6d47bbbcf1ab393d3) .
> The patch is verified on aarch64 . And to add ppc64le support , please modify the files like aarch64 .
> 
> You should modify configure.ac and Makefile.am .
> To obtain best performance , you should add optimized code for ppc64le .

Can you add ppc64le support in next release version? this change is too complex

**Comment by haoyu01** [comment]
We will try to do that .

**Comment by machelcheng** [comment]
Ok, my test system:
# cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

uname -a
Linux localhost 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:37:15 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

**Comment by machelcheng** [comment]
Ok, my test system:
#cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

#uname -a
Linux localhost 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:37:15 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

**Comment by gbtucker** [comment]
It should be possible to build all the units that have base functions but some issues remain.

**Comment by haoyu01** [comment]
@gbtucker and @machelcheng ，

Relative patches has been merged .

**Comment by gbtucker** [comment]
Looks this one was fixed with the merge.
