### ISSUE TITLE
mh_sha256_perf.c test failed on Knight Landing

### ISSUE THREAD

**Issue by Numberist** [intel/isa-l_crypto#23]
Hi,
I have made a test on the KNL X200 machine for avx512 instructions by replacing the update_base and finalize_base with _avx512 in mh_sha256_perf.c. The result is "Illegal instruction". But if I test it with Intel Software Device Emulator, it works. Does the lib mh_sha256_avx512 support KNL?

Thanks.

**Comment by haoyu01** [comment]
Under Linux , cat /proc/cpuinfo , you can check if avx512 is supported on the platform

And you should not change the function to _avx512 . 
ISA-L will check the CPU features and choose the right functions .

**Comment by Numberist** [comment]
From the output of cpuinfo:
bmi1 avx2 smep bmi2 erms avx512f rdseed adx avx512pf avx512er avx512cd xsaveopt dtherm ida arat pln pts
Seems that those avx512 extensions are not supported.

**Comment by gbtucker** [comment]
There is no explicit KNL version.  The avx512 version may rely on an instruction subset not in KNL.  A debugger like gdb should be able to tell you what instruction hits the undef.

**Comment by Numberist** [comment]
I see. Thank you.
