### ISSUE TITLE
 error: '_aligned_malloc' was not declared in this scope

### ISSUE THREAD

**Issue by bolunfeng** [intel/isa-l_crypto#24]
I used the MinGW tool on the Windows 7 platform to compile libisal_crypto.a and libisal.a one by one (gcc compiles each .o file, then ar *.o), but when the link is used, it returns a mistake.

D:/software/gt_compress/lib/win/gcc/debug/intel/isa-l_crypto/include/isa-l_crypto/types.h:52:101: error: '_aligned_malloc' was not declared in this scope
 #   define posix_memalign(p, algn, len) (NULL == (*((char**)(p)) = (void*) _aligned_malloc(len, algn)))
                                                                                                     ^

**Comment by gbtucker** [comment]
Did https://github.com/intel/isa-l/issues/80 answer resolve this issue?
