### ISSUE TITLE
sha1 result is different than openssl

### ISSUE THREAD

**Issue by neutronsharc** [intel/isa-l_crypto#27]
Thank you guys for putting up this great repo.

I tested sha1 code using recommended approach:
mh_sha1_init();
mh_sha1_update();
mh_sha1_finalize();

I computed sha1 of a sample buf "abc".  
Isa-l produces result="a9993e364706816aba3e25717850c26c9cd0d89d"
However openssl produces result="0da4a6f287b334e3a6dc27036323702aaf0b6923".

Have you guys seen this discrepancy?

**Comment by gbtucker** [comment]
Thanks @neutronsharc,

When I do the same I get the first result.
```
$ echo abc | tr -d '\n' | openssl sha1
(stdin)= a9993e364706816aba3e25717850c26c9cd0d89d
```
I tested with isa-l_crypto also and get the same result.

**Comment by neutronsharc** [comment]
Thank you for the reply!

In my last post I made a typo. The openssl gives correct result for input str="abc" 
the sha1="a9993e364706816aba3e25717850c26c9cd0d89d".

However Isa-l gives a different sha1 result="0da4a6f287b334e3a6dc27036323702aaf0b6923".

I use this code snippet of isa-l to generate sha1.  Do you see problem in this code? Thanks.

int GenerateSha1(const void *buf, uint32_t buf_size, void *fp) {
  mh_sha1_ctx *sha1_ctx = malloc(sizeof(mh_sha1_ctx));
  mh_sha1_init(sha1_ctx);
  mh_sha1_update(sha1_ctx, buf, buf_size);
  mh_sha1_finalize(sha1_ctx, fp);
  free(sha1_ctx);
}

**Comment by gbtucker** [comment]
You need `sha1_ctx_mgr_{init, submit, flush}`, not multi-hash if you want SHA1 digest output.  Sorry for the confusion.

Note that multi-buffer hashing works best if you can submit multiple independent hash jobs together.

**Comment by Buristan** [comment]
Thank you for the reply and this issue! May you explain, please, for what purposes I have to use mh_sha1 or mh_sha256?

**Comment by neutronsharc** [comment]
Thank you @gbtucker.  With sha1_ct_mgr_NNNN  I can get the expected sha1 code.
There is a caveat though.  The "SHA1_HASH_CTX.job.result" is uint32_t array,  so the bytes order is different than the openssl result's byte array unless you swap uint32 array bytes.

Another question I found weird.  It seems sha1_ct_mgr_NNN gives different results if I compute sha1 for a buffer chunk in multiple updates, vs in one shot.

For example I have 10K buffer. I can either compute sha1 in 3k+3k+3k+1k incrementals, or compute the entire buffer at once.  The results are different.  Is there buffer alignment or buffer size implications?  Below is my code snippet.

```
  char databuf[10000];
  hash_ctx_init(&ctx);
  sha1_ctx_mgr_submit(&sha1_mgr, &ctx, databuf,             3000, HASH_FIRST);
  sha1_ctx_mgr_submit(&sha1_mgr, &ctx, databuf + 3000, 3000, HASH_UPDATE);
  sha1_ctx_mgr_submit(&sha1_mgr, &ctx, databuf + 6000, 3000, HASH_UPDATE);
  sha1_ctx_mgr_submit(&sha1_mgr, &ctx, databuf + 9000, 1000, HASH_LAST);
  sha1_ctx_mgr_flush(&sha1_mgr);
```
The result is different if I compute all in one:
```
  hash_ctx_init(&ctx);
  sha1_ctx_mgr_submit(&sha1_mgr, &ctx, databuf, 10000, HASH_ENTIRE);
  sha1_ctx_mgr_flush(&sha1_mgr);
```

**Comment by neutronsharc** [comment]
Thanks you @gbtucker !

I still cannot get the isa-l to produce expected result.  Below is my code. Am I wrong?
```
  SHA1_HASH_CTX_MGR sha1_mgr;
  SHA1_HASH_CTX ctx;
  memset(&sha1_mgr, 0, sizeof(sha1_mgr));
  memset(&ctx, 0, sizeof(ctx));

  sha1_ctx_mgr_init(&sha1_mgr);
  hash_ctx_init(&ctx);

  snprintf(databuf, sizeof(databuf) - 1, "abc");
  sha1_ctx_mgr_submit(&sha1_mgr, &ctx, databuf, 3, HASH_ENTIRE);

  sha1_ctx_mgr_flush(&sha1_mgr);

  // Now hash_ctx_digest(&ctx) is the result digest.  However it == ""

```

**Comment by gbtucker** [comment]
@neutronsharc, You must submit independent hash jobs or an update only if you know if the last update is complete.  You might look at the unit test sha1_mb_rand_update_test.c, it uses the returned ctx to index the finished partial update.  From that it knows which new partial update it can resubmit.

**Comment by neutronsharc** [comment]
@gbtucker  By following the example as you indicated everything works perfect.  Thanks!  Appreciate your advice and quick response!

**Comment by gbtucker** [comment]
Thanks, I'll close this issue then.
