### ISSUE TITLE
What is purpose of mh_sha1_ mh_sha256_ functions?

### ISSUE THREAD

**Issue by Buristan** [intel/isa-l_crypto#28]
In a recent issue(https://github.com/intel/isa-l_crypto/issues/27) there was raised the topic about functions mh_sha1_* mh_sha256_*. 
I don't see any profit in these functions, so I have related question: what is the purpose of these functions?

**Comment by gbtucker** [comment]
The purpose of the multi-hash functions is to keep the high throughput of the multi-buffer hashes but with a synchronous interface.  It is best with larger buffers and when you don't need the resulting hash to be standard compliant.  They are often used in dedup applications.

**Comment by Buristan** [comment]
Thanks a lot! Appreciate your quick response!
