### ISSUE TITLE
[Typo Found] Incorrect printf message

### ISSUE THREAD

**Issue by chowo123456** [intel/isa-l_crypto#51]
https://github.com/intel/isa-l_crypto/blob/e38f4beeda838e8fcae401b9349b8a6e83514f13/aes/gcm_ossl_perf.c#L236

It should be "openssl_aes_256_gcm_dec" instead of "openssl_aes_256_gcm_enc".

Regards,
Otto

**Comment by gbtucker** [comment]
Thanks for the notice @chowo123456.  I'll get a fix in.
