### ISSUE TITLE
Can md5_ctx_mgr_submit return non-null CTX to job other than job related tp CTX in argument?

### ISSUE THREAD

**Issue by lucasso** [intel/isa-l_crypto#53]
There is a function:
```
MD5_HASH_CTX* md5_ctx_mgr_submit_sse (MD5_HASH_CTX_MGR* mgr, MD5_HASH_CTX* ctx,
                const void* buffer, uint32_t len, HASH_CTX_FLAG flags);
```
It takes _ctx_ as argument and this _ctx_ is related to some job. Is it possible that as a return value of this _submit..._ function I will get MD5_HASH_CTX* which is related to some other job? E.g. because some other job has already finished. Is it possible?

I can not find an answer neither in documentation comments, nor in the code because it comes to asm files finally. Kindly ask you for answer.

**Comment by gbtucker** [comment]
Yes, this is exactly how it works. The interface is asynchronous. The ctx
of the current job will be returned after a subsequent call, not the
current one.

**Comment by lucasso** [comment]
Thank you very much for a quick answer.
