### ISSUE TITLE
Dependence on endian_helper.h which isn't installed

### ISSUE THREAD

**Issue by jolivier23** [intel/isa-l_crypto#59]
When building my library against latest master, we get the following:

In file included from install/prereq/dev/isal_crypto/include/isa-l_crypto/md5_mb.h:108,
                 from install/prereq/dev/isal_crypto/include/isa-l_crypto.h:20,
                 from src/common/multihash_isal.c:32:
install/prereq/dev/isal_crypto/include/isa-l_crypto/multi_buffer.h:43:10: fatal error: endian_helper.h: No such file or directory
   43 | #include "endian_helper.h"

It seems this file needs to be available or has leaked into external headers.

**Comment by gbtucker** [comment]
Sorry, it missed the distcheck.  I'll have a fix up in a few.
