### ISSUE TITLE
NASM warning: absolute address can not be RIP-relative

### ISSUE THREAD

**Issue by ilmarmors** [intel/isa-l_crypto#6]
Lots of warning: absolute address can not be RIP-relative
when compiling with latest NASM version 2.12.02 (compiled on Jul  6 2016) on CentOS 7

**Comment by gbtucker** [comment]
This is nasm bug https://bugzilla.nasm.us/show_bug.cgi?id=3392361.

**Comment by gbtucker** [comment]
As in [isa-l 16](https://github.com/01org/isa-l/issues/16) it looks like this was fixed in nasm but may take some time to propagate to distros.

**Comment by gbtucker** [comment]
Hopefully everyone has upgraded to a new nasm.
