### ISSUE TITLE
Backtrace from multibuffer MD5 fails due to missing debug info.

### ISSUE THREAD

**Issue by toojays** [intel/isa-l_crypto#8]
If I try to get a backtrace while my program is in the multibuffer MD5 code, I get rubbish, like:

```
(gdb) bt
#0  0x000000000080c0ee in md5_mb_x8x2_avx2 ()
#1  0x0000008000000080 in ?? ()
#2  0x0000008000000080 in ?? ()
#3  0x0000008000000080 in ?? ()
#4  0x0000008000000080 in ?? ()
#5  0x0000000000000000 in ?? ()
```

Here's a description of how to fix this with the GNU Assembler: [CFI directives in assembly files](https://www.imperialviolet.org/2017/01/18/cfi.html). I don't know if YASM supports this syntax. Nor do I know if backtraces are broken on other platforms - I really only care about Linux here.

**Comment by dong-liuliu** [comment]
If you wanna get backtrace, you need to step out from multi-buffer hash internal function to md5_ctx_mgr_submit or md5_ctx_mgr_flush.

At X86 platform, generally RBP register is used to cooperate with RSP and display the backtrace.
But inside ISA-L multibuffer hash internal asm code, RPB is utilized to do hash calculation in order to get better performance. debugger can not get the backtrace when RPB is not cooperating with RSP.

**Comment by toojays** [comment]
The debugger *can* get the backtrace if there is DWARF debugging info that tells it where it can find the saved copy of RBP. See the link in my previous comment.

It might be something like:

```diff
--- md5_mb_x8x2_avx2.asm
+++ md5_mb_x8x2_avx2.asm
@@ -326,7 +326,12 @@ align 32
 
 global md5_mb_x8x2_avx2 :function internal
 md5_mb_x8x2_avx2:
+        ;; Tell assembler to annotate this function with debuginfo.
+        ;; By default, it knows to find previous RSP at RSP+8.
+        .cfi_startproc
 	mov	rax, rsp
+        ;; Tell assembler that previous RSP is now at RAX+8.
+        .cfi_def_cfa rax, 8
 	sub	rsp, STACK_size
 	and	rsp, -32
 	mov	[rsp + _RSP_SAVE], rax
@@ -780,6 +785,7 @@ lastblock:
 	mov	rsp, [rsp + _RSP_SAVE]
 
         ret
+        .cfi_endproc
 
 section .data
 align 64
```

That syntax of the cfi* directives is from the GNU assember. Unfortunately YASM does not accept this syntax.

**Comment by dong-liuliu** [comment]
Although Nasm and Yasm both support DWARF format, neither of them supports CFI directives.
Please just step out to external multibuffer hash API in gdb to get your backtrace.

**Comment by gbtucker** [comment]
Closing as it sounds like not supported by assembler.
