### ISSUE TITLE
Wan to write a Java JNI library wrapper, anything to note about?

### ISSUE THREAD

**Issue by leiless** [intel/isa-l_crypto#82]
Hi all, especially @gbtucker.

I want to write a Java(with JNI) wrapper to use `isa-l_crypto`, is there anything I need to note about?

I'm assuming `isa-l_crypto` will automatically detect instruction capabilities and do the fallback thing. Am I right?
So when I compile the `isa-l_crypto` library from an AVX2-capable machine. and load this library in an AVX-capable(no AVX2) machine, it can automatically use the AVX dispatcher?

```
$ find /usr/lib64 -type f -name "libisal*"
/usr/lib64/pkgconfig/libisal_crypto.pc
/usr/lib64/libisal_crypto.so.2.0.24
/usr/lib64/libisal_crypto.la
/usr/lib64/libisal_crypto.a

$ ldd /usr/lib64/libisal_crypto.so.2.0.24
	linux-vdso.so.1 (0x00007ffc23889000)
	libc.so.6 => /lib64/libc.so.6 (0x00007facddbfe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007facde495000)

$ nm /usr/lib64/libisal_crypto.so.2.0.24 | grep -i glib
                 U __assert_fail@@GLIBC_2.2.5
                 w __cxa_finalize@@GLIBC_2.2.5
                 U memcpy@@GLIBC_2.14
                 U memmove@@GLIBC_2.2.5

```

`libisal_crypto.so` have no other extra runtime dependencies, so it's a pretty portable shared object?

**Comment by gbtucker** [comment]
Yes, isa-l_crypto does detect capabilities to choose appropriate version to run.  This includes AVX and AVX2 when available.

There are no other library dependencies except libc as you see so it is very portable.

You might check the [bindings](https://github.com/intel/isa-l/wiki/Language-Bindings) section for an example of java interface used for isa-l compression.

**Comment by leiless** [comment]
> Yes, isa-l_crypto does detect capabilities to choose appropriate version to run. This includes AVX and AVX2 when available.
> 
> There are no other library dependencies except libc as you see so it is very portable.
> 
> You might check the [bindings](https://github.com/intel/isa-l/wiki/Language-Bindings) section for an example of java interface used for isa-l compression.

Thank you! very informative!
