### ISSUE TITLE
Does a `HASH_CTX` cannot be reuse after it already have >= `*_BLOCK_SIZE` bytes data?

### ISSUE THREAD

**Issue by leiless** [intel/isa-l_crypto#85]
Hi, @gbtucker, I have the following sample program. when I submit >= 64 bytes in a HASH_CTX, and then submit a zero-length array with the same HASH_CTX, I got `HASH_CTX_ERROR_ALREADY_PROCESSING` error.

But when I do the same procedure but have less than 64 bytes in the first submit, it's ok.

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <assert.h>
#include <isa-l_crypto.h>
#include <endian.h>

int main(void) {
    fprintf(stderr, "ISA-L crypto version: %u.%u.%u\n", ISAL_CRYPTO_MAJOR_VERSION, ISAL_CRYPTO_MINOR_VERSION,
            ISAL_CRYPTO_PATCH_VERSION);

    MD5_HASH_CTX_MGR *mgr = NULL;

    int e = posix_memalign((void *) &mgr, 16, sizeof *mgr);
    assert(e == 0);
    assert(mgr != NULL);
    md5_ctx_mgr_init(mgr);

    MD5_HASH_CTX job;
    hash_ctx_init(&job);

    const char *msg = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";
    uint32_t len = strlen(msg);

#if 1
    // Submit >= 64 bytes is NOT OK for later submit()
    MD5_HASH_CTX *ctx = md5_ctx_mgr_submit(mgr, &job, msg, len, HASH_FIRST);
#else
    // Submit < 64 bytes is OK
    MD5_HASH_CTX *ctx = md5_ctx_mgr_submit(mgr, &job, msg, len - 1, HASH_FIRST);
#endif

    if (ctx != NULL) {
        fprintf(stderr, "> #1 ctx->error = %d\n", ctx->error);
        assert(ctx->error == HASH_CTX_ERROR_NONE);
    }
    ctx = md5_ctx_mgr_submit(mgr, &job, NULL, 0, HASH_LAST);
    if (ctx != NULL) {
        fprintf(stderr, "> #2 ctx->error = %d\n", ctx->error);
        assert(ctx->error == HASH_CTX_ERROR_NONE); // L41
    }

    ctx = md5_ctx_mgr_flush(mgr);
    assert(ctx == &job);
    if (ctx->error == HASH_CTX_ERROR_NONE) {
        uint32_t *p = job.job.result_digest;
        printf("%x%x%x%x\n",
               htobe32(p[0]),
               htobe32(p[1]),
               htobe32(p[2]),
               htobe32(p[3])
        );
    } else {
        fprintf(stderr, "> #3 ctx->error = %d\n", ctx->error);
        assert(ctx->error == HASH_CTX_ERROR_NONE);
    }

    free(mgr);
    return 0;
}
```

**Comment by leiless** [comment]
```
$ gcc -Wall -Werror main.c -lisal_crypto && ./a.out
ISA-L crypto version: 2.24.0
> #2 ctx->error = -2
a.out: main.c:41: main: Assertion `ctx->error == HASH_CTX_ERROR_NONE' failed.
[1]    1234432 abort (core dumped)  ./a.out

```

Is this something that is related to the `BLOCK_SIZE`? for example MD5 have 64 bytes block size:
```c
// Hash Constants and Typedefs
#define MD5_DIGEST_NWORDS	4
#define MD5_MAX_LANES		32
#define MD5_MIN_LANES		8
#define MD5_BLOCK_SIZE		64 // This
#define MD5_LOG2_BLOCK_SIZE	6
#define MD5_PADLENGTHFIELD_SIZE	8
```

Meaning when a single job(`HASH_CTX`) had submited >= `BLOCK_SIZE` bytes, later `submit()` will get `HASH_CTX_ERROR_ALREADY_PROCESSING` error.

So we must use a new job(`HASH_CTX`) for a later `submit()` in such a case? Am I right?

**Comment by leiless** [comment]
How can I cumulative calculate the md5 checksum of several input buffers? Just like `md5sum`.
(I can certainly tell that the above sample program usage is something wrong)

**Comment by gbtucker** [comment]
> So we must use a new job(HASH_CTX) for a later submit() in such a case? Am I right?

If it is an update to a previously started job (more data for a single hash job before finalize) you must wait until that job has completed.  There is no way to run pieces of the same hash job in parallel since it is a cryptographic hash, only independent hash jobs can be run together.

> How can I cumulative calculate the md5 checksum of several input buffers? Just like md5sum.

If they are independent checksum jobs (files like in md5sum) then it is possible to submit pieces from each to run in parallel and continue an update by monitoring the returned context and resubmitting.  There are some examples in unit tests and in examples/saturation_test.

**Comment by leiless** [comment]
> If it is an update to a previously started job (more data for a single hash job before finalize) you must wait until that job has completed.

By mean `you must wait until that job has completed`, I need to monitor the returned context(not `NULL`) and submit another job on the returned context?

**Comment by leiless** [comment]
Another question, @gbtucker, as I tested:
Encode a **single** MD5 hash job with 2.0GiB data(`HASH_ENTIRE`), there isn't a significant time difference between ISA-L crypto and JDK 1.7 `MessageDigest("MD5")`

ISA-L crypto and JDK 1.8 LTS both spent around 4.3s to complete.

Is this an expected situation?

Hardware spec:
CPU: i9-9900T (AVX2)
RAM: 32GB (2666MHz)

**Comment by gbtucker** [comment]
The multi-buffer hashing is best utilized by allowing multiple independent hash jobs to run at the same time.  Doing _submit() and then _flush() in sequence as your example code does, will force one job at a time.  Doing it this way will likely be no faster than a single-buffer hash library.  Other examples found with the isa-l_crypto source will show how to keep submitting and re-using context to keep multiple lanes full at all times.

**Comment by leiless** [comment]
> The multi-buffer hashing is best utilized by allowing multiple independent hash jobs to run at the same time.

So I have a single file, I want to give a single hash(like getting md5sum of this single file) value for the whole file, multi-buffer won't speed up in this case?

Since `There is no way to run pieces of the same hash job in parallel since it is a cryptographic hash, only independent hash jobs can be run together.`

In this case, a single whole file cannot be divided into independent parts.

**Comment by leiless** [comment]
> There is no way to run pieces of the same hash job in parallel since it is a cryptographic hash, only independent hash jobs can be run together.

Does this rule apply to all cryptographic hash algorithms? like md5, sha1, sha256, sha512, etc.

Again, thanks for your patient replies!

**Comment by gbtucker** [comment]
> > The multi-buffer hashing is best utilized by allowing multiple independent hash jobs to run at the same time.
> 
> So I have a single file, I want to give a single hash(like `md5sum foobar.bin`) value for the whole file, multi-buffer won't speed up in this case?

No, but if you had `md5sun foo.bin bar.bin ... etc` this could be possible since you would have independent hash jobs.

> Since `There is no way to run pieces of the same hash job in parallel since it is a cryptographic hash, only independent hash jobs can be run together.`
> 
> In this case, a single whole file cannot be divided into independent parts to get a single hash value.

It can be divided but they are dependent.  You must use the results of the previous chunk to process the next and so cannot be run in parallel.

> > There is no way to run pieces of the same hash job in parallel since it is a cryptographic hash, only independent hash jobs can be run together.
> 
> Does this rule apply to all cryptographic hash algorithms? like md5, sha1, sha256, sha512, etc.
> 
> Again, thanks for your patient replies!

That's correct.  This is a property of a cryptographic hash.

**Comment by leiless** [comment]
> **It is important to understand that md5-simd does not speed up a single threaded MD5 hash sum**. Rather it allows multiple independent MD5 sums to be computed in parallel on the same CPU core, thereby making more efficient usage of the computing resources.

https://github.com/minio/md5-simd#md5-simd

What makes me confused is why single-dependent-lane SIMD-MD5 can't be accelerated?
Since my CPU is capable of AVX2, and it should be faster than JDK 1.8 `MessageDigest("MD5")`?

So my question is that why single-lane AVX2-MD5 is not faster than JDK 1.8 MD5 implementation?
JDK 1.8 MD5 seems have no SIMD optimization at all.

**Comment by leiless** [comment]
Hi @gbtucker,
As I looked into https://github.com/intel/isa-l_crypto/blob/master/md5_mb/md5_mb_rand_update_test.c#L109-L134

It seems that when all lanes are full, call `submit()` will likely return `HASH_CTX_ERROR_ALREADY_PROCESSING`, in above code, it resubmit the same job in spin way(keep busy retrying):
```c
		// Resubmit unfinished job
		i = (unsigned long)(ctx->user_data);
		buf_ptr[i] += UPDATE_SIZE;
```

**Comment by gbtucker** [comment]
> It seems that when all lanes are full, call `submit()` will likely return `HASH_CTX_ERROR_ALREADY_PROCESSING`, in above code, it resubmit the same job in spin way(keep busy retrying):

Not quite.  When all lanes are full, a `submit()` will run until at least one job is complete.  This will allow the user to replace the empty lane and keep all lanes full even when jobs/blocks of differing length are submitted.

> 
> ```c
> 		// Resubmit unfinished job
> 		i = (unsigned long)(ctx->user_data);
> 		buf_ptr[i] += UPDATE_SIZE;
> ```

I wouldn't say busy retrying.  The test will just submit a new block to update when a previous update block completes from job i but is not finalized yet.  It uses the ctx->user_data to keep an index of the job number.

**Comment by leiless** [comment]
> Not quite. When all lanes are full, a submit() will run until at least one job is complete.

Glad to hear.

But what if I have several independent hash jobs, and not all lanes full, say, only half of them are full, and in `submit(HASH_FIRST)`, all N independent jobs return `NULL`, how can I know if there any job has completed later on? so I can `submit` the next part of the input.

**Comment by gbtucker** [comment]
> But what if I have several independent hash jobs, and not all lanes full, say, only half of them are full, and in `submit(HASH_FIRST)`, all N independent jobs return `NULL`, how can I know if there any job has completed later on? so I can `submit` the next part of the input.
> > all N independent jobs return `NULL`
> 
> Can this even happen? (I haven't do my experiment)

A return of null usually means lanes are not yet full.  The underlying multi-buffer hashing routine will only run on submit() and all lanes are full or flush() is called.  You can check the jobs status at any time but using the returned context as a clue as to what to put next is a solid method to keep from ever searching.

**Comment by leiless** [comment]
```c
HASH_CTX *ctx, *avai_ctx = NULL;

    for (uint64_t i = 0; file_size > 0; i++) {
        len = MIN(CHUNK_MAP_SIZE, file_size);
        mem = (char *) mmap(NULL, len, PROT_READ, MAP_SHARED, fd, offset);
        assert(mem != MAP_FAILED);

        if (avai_ctx == NULL) {
            avai_ctx = &ctx_arr[i % MAX_LANES];
        }
        avai_ctx = ctx_mgr_submit(mgr, avai_ctx, mem, len, HASH_ENTIRE);
        if (avai_ctx != NULL) {
            count++;
        } else {
            empty++;
            assert(i < 7); // AVX2
        }

        e = munmap(mem, len);
        assert(e == 0);
        offset += len;
        file_size -= len;
    }

    while ((ctx = ctx_mgr_flush(mgr)) != NULL) { // Segmentation fault (core dumped)
        count++;
    }
```

Hi, @gbtucker, As I followed your suggestion, I read a large file in chunks (each time 4MB), and calculate SHA256 for each 4MB chunk, but I got segfault when I do `ctx_mgr_flush`.

Basically, I just want to do SHA256 calc parallelly for each 4MB chunk.
I have no idea what's going wrong, sorry to bother you again.

**Comment by leiless** [comment]
> Hi, @gbtucker, As I followed your suggestion, I read a large file in chunks (each time 4MB), and calculate SHA256 for each 4MB chunk, but I got segfault when I do ctx_mgr_flush.

Got it, the segfault is caused by `munmap()`, after unmap, the page memory will be invalidated, hence memory access got `SIGSEGV` signal.
